### ISSUE TITLE
auto-removal of dakuten in 2nd verse

### ISSUE THREAD

**Issue by woonie** [GoldenChrysus/KarutaSRS#20]
![ss (2020-03-18 at 11 51 24)](https://user-images.githubusercontent.com/1450835/76973611-86af1c80-6973-11ea-8bb2-b845bf8d2b49.png)

Is it possible to implement auto-removal of dakuten eg. type in ga -> resolve as ka? In this case, the [original poem](http://www.samac.jp/search/poems_detail.php?id=55) is nagare, but dakuten doesn't appear on the torifuda so it's printed as nakare.

**Comment by GoldenChrysus** [comment]
The intent of second-verse testing in Karuta SRS is to help people learn what's on the cards visually, not necessarily what the real poem text is. Therefore, I consider it correct functionality to mark が as incorrect if the text on the card is か. I understand this may put you at a "disadvantage" of sorts if you know the real poem, but it's not possible to differentiate between someone who makes a mistake because they know the real poem and someone who simply misremembers what the character should have been.
