### ISSUE TITLE
help with running?

### ISSUE THREAD

**Issue by kufii** [GoldenChrysus/KarutaSRS#3]
Hey! I stumbled across this project and since I'm trying to learn the Hyakunin Isshu I was curious to check out what it was like in it's current state. I'm having some trouble running it though.

What confuses me is that the Ember app seems to make api requests to the rails backend on the same port, but I can not run these 2 projects on the same port. So the ember app runs on port 4200, and tries to call the /poems endpoint on port 4200 instead of port 3000 which the server is running on, so I get a 404 error. What am I doing wrong?

**Comment by GoldenChrysus** [comment]
Hey! Thanks for checking out the project.

The docs are pretty nonexistent right now because I wasn't expecting any to try building this yet. If you want to wait ~2-3 days, the fully-featured version will be available at https://karutasrs.com/.

---

If you still want to try building locally, you need to first have a Postgres install (I guess you could use a different DBMS but that would require modifying the Rails database config). Then copy the /karutasrs-api/config/application.yml.sample file to application.yml in the same directory and configure it with your database info. If you want to be able to use Rails to create the database itself, your Postgres user needs to be able to create databases. I personally prefer to create all the databases from within pgAdmin or Webmin or something.

Hopefully you know how to build a Rails app, but if not, the gist is: in /karutasrs-api, you need to run:
1. `bundle install`
2. Then if you choose to use Rails to create the database itself (and not just the schema), you need to run `rake db:create`
3. Then run `rake db:migrate` to populate the schema
4. Finally run `rake db:seed` to seed the poems

You can run the Rails app in development mode using `rails s -d` (`-d` runs as daemon).

----

Then the problem you're having with the Ember app trying to access the API on 4200 is probably just a missing config file. /karutasrs-front/config/config.yml.sample should be copied to config.yml in the same directory. The `api_host` should just point to your Rails app; since the Rails app is namespaced to `/api` the api_host should end in /api. For example, for local development on my Windows machine, the api_host is `http://192.168.1.165:3000/api`.

I'm assuming you know how to build the Ember app since you've at least got it attempting to make server calls, but just be sure the run `npm install` and then `ember s` within /karutasrs-front.

----

Otherwise, like I mentioned, the full version should be available in a few days. I just need to scrape some more cultural background info from a site that fortunately allowed me to republish their information, and then work that into the database schema and various components. As well as scrape the English translations. Then create a guide on how to use the site and how the review system works. All in all I expect a working (but technically alpha) version up this weekend or earlier next week.

Included are some photos of the site so you can see what to expect:

https://i.imgur.com/KLaCiFq.png

https://i.imgur.com/r90ek1E.png

https://i.imgur.com/tQlsFAq.png

https://i.imgur.com/FjF3W6i.png

https://i.imgur.com/E73WnCo.png

**Comment by kufii** [comment]
Thank you! This helps a lot. Great first impressions
