### ISSUE TITLE
cards too big at tablet width for lessons

### ISSUE THREAD

**Issue by kufii** [GoldenChrysus/KarutaSRS#5]
![image](https://user-images.githubusercontent.com/4913552/71590424-60a57900-2af6-11ea-8240-6f2b840e0c6b.png)

This makes it not as nice as it could be to use on my tablet. I was messing around and at tablet sizes, the 2 column layout still looks really good

**Comment by kufii** [comment]
Also, I'd be willing to do some PRs for this project, this is probably a good first issue to tackle so if it's ok with you feel free to leave it to me

**Comment by GoldenChrysus** [comment]
Okay. I don't have contribution info setup here but you can reference the ones at https://github.com/GoldenChrysus/ffxiv-ember-overlay#contributing. I'm fairly strict on the style being consistent with existing code.

You'll also have to recalculate the font size for the card hiragana in `/app/styles/components/grabber-card.less`. The formula I'm using to roughly calculate the `vw` size is `((card_width * .1478) / (viewport_width * 0.01)) * 1.4086`. `card_width` is the width of the card, excluding any margins or padding (so red edge to red edge, including the edges) as indicated by Chrome inspect, and `viewport_width` is the width of the body reported by Chrome inspect. Sometimes the size needs to be finely adjusted from there so that the whitespace around the characters is even all around (usually the issue is that the characters are too large so the whitespace at the bottom of the card is significantly less than the rest of the card).

Relevant styling should be `.grabber-card-outer.standalone-lesson` in the `max-width: @computerBreakpoint - 1` block (if I remember correctly).

----

I assume the cards are too large for reviews at table size as well, but please make a separate issue if you want to resolve that as well.

**Comment by kufii** [comment]
sorry I submitted the PR before seeing this comment. I'm pretty good with following style (I am also very strict about style for PRs for my projects). I simply used the same font size as the computer width and from my testing it looks good. of course let me know if you want anything changed
